program DiaDeLaSemana;

var
  dia: Integer;

begin
  writeln('Ingrese un numero del 1 al 7:');
  readln(dia);

  case dia of
    1: writeln('Lunes');
    2: writeln('Martes');
    3: writeln('Miercoles');
    4: writeln('Jueves');
    5: writeln('Viernes');
    6: writeln('Sabado');
    7: writeln('Domingo');
  else
    writeln('Numero invalido. Por favor ingrese un numero del 1 al 7.');
  end;
  Readln
end.